[package]
name = "shared-school-project"
version = "0.1.0"
edition = "2024"

[dependencies]
simulation = { path = "../modules/simulation" }
graphics = { path = "../modules/graphics" }
types = { path = "../modules/types" }

macroquad = "0.4.14"
fastrand = "2.3.0"